# Generated by Django 5.2.4 on 2026-06-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_bio_remove_customuser_github_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="surname",
            field=models.CharField(blank=True, max_length=150, verbose_name="Фамилия"),
        ),
    ]
