# Generated by Django 5.2.4 on 2026-06-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на GitHub"),
        ),
    ]
