# Generated by Django 5.2.4 on 2026-06-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Описание проекта"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название проекта"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                max_length=124, unique=True, verbose_name="Название навыка"
            ),
        ),
    ]
