# Generated by Django 5.2.4 on 2026-06-10 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_rename_title_project_name_project_github_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="author",
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор проекта",
            ),
            preserve_default=False,
        ),
    ]
